name = "ModGay"
author = "Dojoji"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26118fbf0cf1b8a5efdbc4e1023a281bfdee9d77fc0fb7e0750096b924bb1964"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
