name = "milomc"
author = "MiloHakai x Dojoj"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b16bd91b5441b14f98d01c12c9ea675d9902087a7a4530c068d8fd30bedabe7e"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
