name = "ModpackMC"
author = "MiloHakai x Dojoj"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c46960551fd19d90776949120d5b4ee89c32379ca950e4905db1faa37ee8f928"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
