name = "milomc"
author = "MiloHakai x Dojoj"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bc87a6536c961fbb521851c9653c1f05cc034db769de50d8a8905ff53196ab1"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
