
[general]
	disable_mod = false
	auto_start = false
	space_modules = false
	shadow_text = true
	animations = true
	animationSpeed = 1.0
	fontScale = 1.0
	background_color = 1867534416
	hide_debug_crosshair = false
	hide_sidebar = true
	hide_bossbar = true
	always_show_profiler = false
	always_show_tps = false

[[modules_left]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "minecraft"
	name_color = 10861055
	value_color = 6447801
	enabled = true

	[modules_left.lines]
		minecraft = true

[[modules_left]]
	name = "fps"
	color_high = 9276860
	color_med = 9276860
	color_low = 16733525
	enabled = true

	[modules_left.lines]
		fps = true

[[modules_left]]
	name = "graphics"
	name_color = 10861055
	value_color = 9276860
	enabled = true

	[modules_left.lines]
		render_distance = true
		graphics = true
		clouds = true
		biome_blend_radius = true
		shader = true

[[modules_left]]
	name = "server"
	name_color = 10861055
	value_color = 16777215
	enabled = true

	[modules_left.lines]
		server_tick = true
		packets_sent = true
		packets_received = true

[[modules_left]]
	name = "coords"
	name_color = 14404351
	color_x = 10861055
	color_y = 7828198
	color_z = 6447849
	enabled = true

	[modules_left.lines]
		player_coords = true
		block_coords = true
		chunk_relative_coords = true
		chunk_coords = true

[[modules_left]]
	name = "location"
	name_color = 10861055
	value_color = 6447849
	enabled = true

	[modules_left.lines]
		dimension = true
		facing = true
		rotation = false
		light = true
		light_server = false
		highest_block = true
		highest_block_server = false
		biome = true
		local_difficulty = true
		day_ticks = false
		days_played = false
		slime_chunk = true

[[modules_left]]
	name = "chunks"
	name_color = 43775
	value_color = 16777045
	chunks_enabled_color = 5635925
	chunks_disabled_color = 16733525
	total_chunks_color = 16755200
	enabled = false

	[modules_left.lines]
		chunk_sections = true
		chunk_culling = true
		pending_chunks = true
		pending_uploads = true
		available_buffers = true
		client_chunk_cache = true
		loaded_chunks = true
		loaded_chunks_server = true
		forceloaded_chunks = true
		spawn_chunks = true
		chunk_file = true

[[modules_left]]
	name = "entity"
	name_color = 16733525
	value_color = 16777045
	total_entities_color = 16755200
	enabled = false

	[modules_left.lines]
		particles = true
		entities = true
		monster = true
		creature = true
		ambient = true
		axolotls = true
		underground_water_creature = true
		water_creature = true
		water_ambient = true
		misc = true
		werewolves_werewolf = true
		vampirism_hunter = true
		vampirism_vampire = true
		eitd_eyes = true

[[modules_left]]
	name = "sound"
	name_color = 16755200
	value_color = 5636095
	maximum_color = 43690
	enabled = false

	[modules_left.lines]
		sounds = true
		ambient_sounds = true
		mood = true

[[modules_left]]
	name = "help"
	name_color = 10861055
	value_color = 6447801
	enabled_color = 5635925
	disabled_color = 16733525
	enabled = true

	[modules_left.lines]
		pie_graph = false
		fps_tps = true
		help = true

[[modules_left]]
	name = "miscleft"
	name_color = 16645526
	value_color = 5636095
	enabled = false

	[modules_left.lines]
		misc_left = true

[[modules_right]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "empty"
	empty_lines = 1
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "system"
	name_color = 10861055
	value_color = 6447801
	enabled = true

	[modules_right.lines]
		time = true
		java_version = true
		memory_usage = true
		allocation_rate = true
		allocated_memory = true
		cpu = true
		display = true
		gpu = true
		opengl_version = true
		gpu_driver = true

[[modules_right]]
	name = "miscright"
	name_color = 16645526
	value_color = 5636095
	enabled = false

	[modules_right.lines]
		misc_right = true

